<?php
if(!isset($_POST['con_submit']))
{
  //This page should not be accessed directly. Need to submit the form.
  header('Location: ../');
  //echo 'derpderpderp';
} 

require'PHPMailer/PHPMailerAutoload.php';

$res = true;
$err = "";

session_start();
if( isset($_POST["captcha"]) && $_POST["captcha"] != "" && $_SESSION["code"] == $_POST["captcha"] ) {
  //echo "Correct Code Entered";
  $res = true;
  //Do you stuff
} else {
  //die("Wrong Code Entered");
  $res = false;
  $err .= "Wrong captcha code entered\n";
}

$fname = $_POST['fname'];
$lname = $_POST['lname'];
$email = $_POST['email'];
$subject = $_POST['subject'];
$message = $_POST['message'];

$fullname = $fname . " " . $lname;

if(IsInjected($email)) {
    $res = false;
    $err = "Bad email value\n";
}

if ($res) {

  $mail = new PHPMailer;
  $mail->setFrom('site@prblmtq.com', 'PRBLMTQ');
  $mail->AddReplyTo($email, $fullname);
  $mail->addAddress('pat@prblmtq.com', 'Pat Ripley');
  $mail->Subject  = $subject;
  $mail->Body     = "Recieved a message from prblmtq.com!\n\nName: " . $fullname . "\nEmail: " . $email . "\n\n" . $message . "\n\nEmail generated by prblmtq.com.\nTo respond to the user, hit reply and it will send a reply to the email the user provided.";
    if(!$mail->send()) {
    $res = false;
    $err .= "Email message not sent: " . $mail->ErrorInfo;
  } else {
    $res = true;
  }
}


// Function to validate against any email injection attempts
function IsInjected($str) {
  $injections = array('(\n+)',
              '(\r+)',
              '(\t+)',
              '(%0A+)',
              '(%0D+)',
              '(%08+)',
              '(%09+)'
              );
  $inject = join('|', $injections);
  $inject = "/$inject/i";
  if(preg_match($inject,$str)) {
    return true;
  } else {
    return false;
  }
}

?>

<html lang="en" id="contact-submission-page">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>PRBLMTQ</title>
  <link rel="icon" type="image/png" href="../images/p.png">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Custom CSS -->
    <link href="../css/style.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,600,700" rel="stylesheet" type="text/css" />

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="../js/countdown.js"></script>

</head>
<body>
  <div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <div class="container-fluid text-center rounded">
      <?php 
          if($res === true) {
            echo '<span class="glyphicon glyphicon-send logo margin"></span>';
            echo '<div class="alert alert-success margin">';
            echo '<p><strong>Success!</strong><br>Thanks ' . $_POST['fname'] . '!<br>I\'ll try my best to get back to you<br>within 1-2 business days!</p>';
            echo '</div>';
            echo '<p>You will be redirected in <span id="counter">10</span> second(s).<br>Click <a href="http://www.prblmtq.com">here</a> to go there directly.</p>';
          } elseif($res === false) {
            echo '<span class="glyphicon glyphicon-remove logo margin"></span>';
            echo '<div class="alert alert-danger margin">';
            echo '<p><strong>Sorry!</strong><br>' . $err . '</p>';
            echo '</div>';
            echo '<p>Click <a href="javascript:history.back()">here</a> to go back.</p>';
          } ?>
    </div>
  </div>
  <div class="col-sm-4"></div>
  </div>
</body>
</html>